spring:
  data:
    mongodb:
      uri: mongodb://mongodb.test.svc.cluster.local:27017/ail-location
  datasource:
    url: jdbc:mysql://mysql-svc.debug.svc.cluster.local:3306/xsun_gps?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: xsun_group
    password: 3Ar7PNJ0lRsQ1BPJ
  redis:
    database: 0
    host: redis-svc.debug.svc.cluster.local
    port: 6379
  rabbitmq:
    addresses: rabbitmq-svc.debug.svc.cluster.local
    port: 61613
    username: user
    password: password
swagger:
  enable: true
abs:
  queue:
    default: abs.default.debug
jimi:
  expires_in: 100
  mapType_google: GOOGLE
xinya:
  xsungroupurl: http://xinya-svc.debug.svc.cluster.local:8080
scheduler:
  close: true
